.env.development
.env.example
package-lock.json
package.json
src/app.module.ts
src/app.service.ts

Configure Environment Variables & ConfigModule #2

Configure Environment Variables & ConfigModule #2

---

.github/workflows/ci-cd.yml

This PR introduces a fully automated CI/CD pipeline for the StrellerMinds backend. The pipeline ensures that every commit and pull request undergoes linting, testing, and building before merging. Additionally, successful builds are automatically deployed to the production server.
🚀 Key Features:
🛠 Linting & Code Quality Checks to enforce standards.
✅ Automated Testing with Jest for reliability.
📦 Build Process to generate production-ready code.
🚀 Deployment to Production using GitHub Actions & SSH.
Impact on the Project:
Removes manual deployment efforts, reducing errors.
Ensures every commit is validated before merging.
Improves release speed and reliability.

Automated CI/CD Pipeline for StrellerMinds Backend

---

src/courses/courses.module.ts
src/courses/dtos/course-review.dto.ts
src/courses/dtos/create.category.dto.ts
src/courses/dtos/create.course.dto.ts
src/courses/dtos/create.course.moduledto.ts
src/courses/dtos/createetagdto.ts
src/courses/dtos/query-course.dto.ts
src/courses/dtos/update-course-reviewdto.ts
src/courses/dtos/update.category.dto.ts
src/courses/dtos/update.course.dto.ts
src/courses/dtos/update.coursemodule.dto.ts
src/courses/dtos/updatetagdto.ts
src/courses/entities/category.entity.ts
src/courses/entities/course-module.entity.ts
src/courses/entities/course-review.entity.ts
src/courses/entities/course.entity.ts
src/courses/entities/tag.entity.ts
src/users/entities/user.entity.ts

course-module dto and entities relationship created and completed

course-relationship-complete_

---

src/main.ts
src/role/protected.controller.ts
src/role/roles.decorator.ts
src/role/roles.enum.ts
src/role/roles.guard.ts

This PR introduces Role-Based Access Control (RBAC) to manage user permissions effectively. It ensures that only authorized users can access specific endpoints based on their roles.
Key Features Implemented
✅ User Roles Definition (roles.enum.ts)
Defined Admin, Instructor, and Student roles using an enum.
✅ Custom Role Decorator (roles.decorator.ts)
Introduced @Roles() decorator to assign roles to routes.
✅ Roles Guard for Authorization (roles.guard.ts)
Implemented RolesGuard to restrict access based on assigned roles.
✅ Secure API Endpoints (protected.controller.ts)
Created a ProtectedController with role-specific routes:
Admin Route (/protected/admin)
Instructor Route (/protected/instructor)
Student Route (/protected/student)
✅ Global Guard Integration (main.ts)
Applied RolesGuard …

Implemented role based access control logic

---

src/auth/auth.controller.ts
src/auth/auth.service.ts
src/auth/dto/auth-response.dto.ts
src/auth/dto/login.dto.ts
src/auth/entities/auth-token.entity.ts

- Added one-to-many relation between User and AuthToken
- Configured cascade delete and indexing for AuthToken
Integrate AuthToken relation into the User entity. This update links users with their auth tokens, ensuring proper cascade deletion and efficient lookups. It lays the groundwork for advanced token management in future enhancements.

feat(user): add auth token relation

---

src/modules/lesson/dto/create-lesson.dto.ts
src/modules/lesson/dto/update-lesson.dto.ts
src/modules/lesson/entities/lesson.entity.ts
src/modules/lesson/enums/lesson-type.enum.ts

Implementation of Lesson Module Entities and DTOs

Implement Lesson Module Entities and DTOs

---

package-lock.json
package.json
src/app.module.ts
src/ipfs/README.md
src/ipfs/ipfs.controller.ts
src/ipfs/ipfs.module.ts
src/ipfs/ipfs.service.spec.ts
src/ipfs/ipfs.service.ts

This pull request introduces an IPFS integration service within the StrellerMinds-Backend project, enabling decentralized content storage and retrieval. 
Key features include:
IPFS Client Integration: Utilizes ipfs-http-client for interacting with the InterPlanetary File System.
Content Storage and Pinning: Provides endpoints for storing content on IPFS with pinning for persistence.
Content Retrieval and Caching: Implements caching using NodeCache to enhance retrieval efficiency and availability.
Content Verification: Adds functionality to verify content integrity using hashes.
Comprehensive Testing: Includes unit and integration tests to ensure the reliability of IPFS functionalities.
Documentation: Detailed documentation of IPFS-related endpoints and usage instructions.
This integration …

Implement IPFS Integration for Decentralized Content Storage

---

src/notifications/dto/create-notification-from-template.dto.ts
src/notifications/dto/create-notification.dto.ts
src/notifications/dto/notification-preference.dto.ts
src/notifications/dto/query-notifications.dto.ts
src/notifications/dto/update-notification.dto.ts
src/notifications/entities/notification-preference.entity.ts
src/notifications/entities/notification-template.entity.ts
src/notifications/entities/notification.entity.ts
src/notifications/notification-delivery.service.ts
src/notifications/notifications.controller.ts
src/notifications/notifications.gateway.ts
src/notifications/notifications.module.ts
src/notifications/notifications.service.ts
src/notifications/providers/email.service.ts
src/notifications/providers/push-notification.service.ts

This project aims to create a notification service that manages in-app notifications, email notifications, and push notifications. The service will provide API endpoints for managing notifications and user preferences, ensuring a flexible and scalable notification system.
- Implement a storage mechanism for storing notifications (e.g., database, in-memory store).
- Implement delivery methods for sending notifications to users (email, push, in-app).
- Define various notification types (e.g., system updates, user actions, reminders).
- Create customizable templates for each notification type, allowing dynamic content generation.
- Implement user preferences for controlling the types and delivery methods of notifications.
- Allow users to enable/disable specific notifications, set …

added the multi channel notification

---

src/users/dtos/create.users.dto.ts

- Defined permission sets for three roles: student, mentor, and admin
- Implemented role assignment during user creation and update processes
- Developed middleware for validating role-based access to API endpoints
- Integrated role information in JWT tokens to ensure correct access permissions
- Created admin-only API endpoints for managing roles (user creation, update, and deletion)
- Added comprehensive error handling and logging for unauthorized access attempts
- Ensured compliance with project coding standards and security guidelines
- Wrote unit and integration tests to cover key RBAC functionalities

 Implement role-based access control (RBAC) system

---

.env.example
src/app.module.ts
src/soroban/dto/create-soroban.dto.ts
src/soroban/dto/credential.dto.ts
src/soroban/dto/update-soroban.dto.ts
src/soroban/entities/credential-record.entity.ts
src/soroban/entities/soroban.entity.ts
src/soroban/soroban.controller.spec.ts
src/soroban/soroban.controller.ts
src/soroban/soroban.module.ts
src/soroban/soroban.service.spec.ts
src/soroban/soroban.service.ts

This PR implements the backend service responsible for minting verifiable credentials on the Stellar blockchain using Soroban smart contracts.
- Integration with Soroban smart contracts to mint credentials.
- Handles transaction construction, signing, and submission.
- Implements retry logic and error handling for failed transactions.
- Stores transaction records and credential references in the database.
- Adds initial documentation for the minting flow and contract interaction.
- Credential minting should trigger a signed Soroban transaction.  
- Transactions must be submitted to the Stellar network and recorded.  
- All failures are logged, and retry logic is in place for transient issues.  
- Unit/integration tests simulate blockchain interactions with mocks.
- Adheres to Stellar best …

Feature: Mint Verifiable Credentials via Soroban on Stellar

---

src/assignment/assignment.controller.spec.ts
src/assignment/assignment.service.spec.ts
src/certificate/certificate.controller.spec.ts
src/certificate/certificate.service.spec.ts
src/course/course.controller.spec.ts
src/course/course.service.spec.ts
src/email/email.controller.spec.ts
src/email/email.service.spec.ts
src/enrollment/enrollment.controller.spec.ts
src/forum/forum.controller.spec.ts
src/forum/forum.service.spec.ts
src/grading/controller/grading.controller.spec.ts
src/moderation/moderation.controller.spec.ts
src/moderation/moderation.service.spec.ts
src/notification/notification.controller.spec.ts
src/notification/notification.service.spec.ts
src/payment/payment.controller.spec.ts
src/payment/payment.service.spec.ts
src/post/post.controller.spec.ts
src/post/post.service.spec.ts
src/progress/progress.controller.spec.ts
src/progress/progress.service.spec.ts
src/soroban/soroban.controller.spec.ts
src/submission/submission.controller.spec.ts
src/submission/submission.service.spec.ts
src/topic/topic.controller.spec.ts
src/topic/topic.service.spec.ts
src/user-profiles/user-profiles.controller.spec.ts
src/users/users.controller.spec.ts
src/users/users.service.spec.ts

This PR increases unit test coverage across the codebase to at least 85%. The following changes were made:
- Added tests for core services and components.
- Ensured critical paths and edge cases are covered.
- Set up coverage reporting.
- Documented testing gaps with rationale.
Closes #100
- Added unit tests for all completed modules.
- Mocked external dependencies using Jest where appropriate.
- Integrated coverage reporting and ensured the 85% and more target is met.

PR for Achieve 85%+ Unit Test Coverage

---

.env.development
src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/auth.service.ts
src/auth/strategies/auth-strategy.interface.ts
src/auth/strategies/jwt-local.strategy.ts

- Modularized authentication logic via `IAuthStrategy` and `JwtLocalStrategy`.
- Registered strategy providers using a `useFactory` for future extensibility (e.g. Google, Wallet, OTP).
- Applied dependency injection for configuration and services to reduce tight coupling.
- Introduced global guards (`JwtAuthGuard`, `RolesGuard`) using `APP_GUARD`.
- Improved error handling in strategy and service layers using NestJS exception classes.
- Cleaned up AuthService by moving credential logic to a dedicated strategy.

modularize and refactor strategies for scalability

---

src/verification/dto/verify-credential.dto.ts
src/verification/strategies/eth-signature.strategy.ts
src/verification/strategies/ipfs-proof.strategy.ts
src/verification/strategies/jwt.strategy.ts
src/verification/test/verification.service.spec.ts
src/verification/verification.controller.ts
src/verification/verification.module.ts
src/verification/verification.service.ts

This PR delivers a full implementation of a credential verification API supporting blockchain-based validation techniques. It covers Ethereum signature checks, JWT token validation, and IPFS CID verification, following security and documentation best practices.
---
- **Credential Verification Endpoint**
- `POST /verify-credential` supports multiple verification methods
- **Supported Methods**
- `eth_signature` - Verifies Ethereum message signatures using `ethers.js`
- `jwt` - Verifies JSON Web Tokens
- `ipfs_proof` - Validates IPFS CIDs and hashes the content
- **Tamper Detection**
- SHA-256 hash comparisons and signature validation
- **Modular Strategy Pattern**
- Cleanly supports future extensibility for additional methods
- **Swagger Documentation**
- Fully documented endpoint and DTO …

feat(verification): implement complete credential verification API with multi-method support

---

docs/blockchain-monitoring.md
src/blockchain/blockchain.controller.ts
src/blockchain/blockchain.module.ts
src/blockchain/blockchain.service.ts
src/blockchain/monitoring.service.spec.ts
src/blockchain/monitoring.service.ts

The blockchain transaction monitoring service has been successfully created and implemented according to the below task and all the criteria were met.
Implemented a service to monitor and track blockchain transactions related to the platform.
Acceptance Criteria
Tracked transaction status
Implemented confirmation handling
Added notification system
Created transaction history
Document monitoring approach
Technical Guidelines
Researched monitoring options
Documented service architecture
closes[#181]

Blockchain transaction service created

---

.env.example
docs/backup-recovery.md
package-lock.json
package.json
src/app.module.ts
src/backup/backup-retention.service.ts
src/backup/backup-verification.service.ts
src/backup/backup.controller.ts
src/backup/backup.module.ts
src/backup/backup.service.spec.ts
src/backup/backup.service.ts
src/mentorship/services/mentorship.service.ts

Implements a comprehensive automated backup system for database and application data with verification, retention policies, and recovery documentation.
- **Scheduled Backups**: Daily DB backups (2 AM) + Weekly app data backups
- **Verification**: Automatic backup validation with restore testing
- **Retention**: Configurable cleanup policies (30 days + 12 months monthly)
- **Manual Control**: REST API endpoints for on-demand backups
- **Documentation**: Complete recovery procedures
- `BackupService`: Main orchestration with cron scheduling
- `BackupVerificationService`: Validates backup integrity
- `BackupRetentionService`: Manages cleanup policies
- `BackupController`: Manual backup endpoints
- Unit tests for all backup services
- Mock implementations for external dependencies
- Backup …

feat: implement automated backup system with verification and retention

---

src/dashboard-analytics/analytics.controller.ts
src/dashboard-analytics/analytics.module.ts
src/dashboard-analytics/analytics.service.ts
src/dashboard-analytics/dto/analytics-query.dto.ts
src/dashboard-analytics/dto/analytics-response.dto.ts
src/dashboard-analytics/entities/course-completion.entity.ts
src/dashboard-analytics/entities/user-engagement.entity.ts
src/dashboard-analytics/guards/analytics-auth.guard.ts
src/dashboard-analytics/interceptors/analytics-logging.interceptor.ts

This PR introduces a new **Analytics Dashboard API** designed to provide key engagement and performance metrics for administrators and instructors. The API supports filtering, export capabilities, and adheres to authorization requirements.
---
**Priority:** Medium  
**Estimated Effort:** Medium  
---
The new API endpoint(s) enable access to analytics data relevant to user engagement and course performance. The goal is to give admins and instructors actionable insights through key metrics.
---
- 📊 Track **user engagement metrics**
- ✅ Include **course completion rates**
- 🔍 Support **filtering** by user, course, and **time range**
- 📤 Enable **data export functionality**
- 🔐 Implement **authorization** to restrict access
---
- ⚙️ Optimized database **queries** for performance
- 📘 …

added dashboard analytics

---

src/blockchain/soroban/contracts/Cargo.toml
src/blockchain/soroban/contracts/README.md
src/blockchain/soroban/contracts/course_achievements.rs
src/blockchain/soroban/contracts/test.rs

Introduce a new Soroban smart contract for managing course achievements on the Stellar network. The contract provides functionality to:
- Issue achievements to users with metadata URI
- Verify user ownership of specific achievements
- Retrieve all achievements for a given user Includes comprehensive unit tests and detailed documentation in README.md
closes #180

feat(soroban): add course achievements smart contract

---

src/app.module.ts
src/cache/cache.interceptor.spec.ts
src/cache/cache.module.ts
src/cache/cache.service.spec.ts
src/cache/controllers/cache-management.controller.ts
src/cache/decorators/cache-key.decorator.ts
src/cache/decorators/cache-ttl.decorator.ts
src/cache/decorators/cacheable.decorator.ts
src/cache/enums/cache-strategy.enum.ts
src/cache/guards/cache-condition.guard.ts
src/cache/interceptors/cache-invalidation.interceptor.ts
src/cache/interceptors/cache.interceptor.ts
src/cache/interfaces/cache-config.interface.ts
src/cache/interfaces/cache-strategy.interface.ts
src/cache/services/cache-invalidation.service.ts
src/cache/services/cache-manager.service.ts
src/cache/services/cache.service.ts
src/config/cache.config.ts
src/products/products.controller.ts
src/users/users.controller.ts

Closes #166  
This PR introduces response caching to enhance API performance, reducing latency for frequently accessed data.  
- Identified cacheable endpoints for optimization  
- Implemented cache strategy using appropriate caching mechanisms  
- Added cache invalidation logic to maintain data accuracy  
- Configured cache timeouts for efficient expiration management  
- Documented caching approach and configuration for clarity  
- Ensured proper error handling for caching operations  
- Developed cache verification tests to validate behavior  
```
1. Run automated tests using:  
```bash
npm run test
```  
Ensure caching functions operate properly  
```

Feat: Implemented Response Caching for Performance Optimization

---

src/audit-log/audit-log.module.ts
src/audit-log/controllers/audit-log.controller.ts
src/audit-log/decorators/audit-log.decorator.ts
src/audit-log/dto/audit-log-filter.dto.ts
src/audit-log/dto/audit-log-response.dto.ts
src/audit-log/dto/create-audit-log.dto.ts
src/audit-log/entities/audit-log.entity.ts
src/audit-log/guards/audit-log-access.guard.ts
src/audit-log/interceptors/audit-log.interceptor.ts
src/audit-log/services/audit-log-retention.service.ts
src/audit-log/services/audit-log.service.ts
src/audit-log/tests/audit-log-retention.service.spec.ts
src/audit-log/tests/audit-log.controller.spec.ts
src/audit-log/tests/audit-log.service.spec.ts

This PR implements a comprehensive audit logging system for tracking admin actions with the following features:
- **Entity & Database**: Added `audit_logs` table with proper indexes and PostgreSQL enums
- **Core Components**: Created service, controller, interceptor, and decorator for flexible logging
- **Security**: Implemented checksum verification, access controls, and data sanitization
- **Retention**: Added configurable retention policies with automated cleanup
- **API Endpoints**: Created endpoints for viewing, filtering, and analyzing logs
- **Documentation**: Added detailed usage examples and SQL scripts
This implementation ensures compliance requirements are met while providing robust security and performance optimizations.
closes #130

Implement Audit Log Feature for Admin Actions

---

package-lock.json
package.json
src/app.e2e-spec.ts
src/main.ts

response compression

---

src/email-verification/auth.module.ts
src/email-verification/auth.service.ts
src/email-verification/dto/email-verification.dto.ts
src/email-verification/email-verification.controller.ts
src/email-verification/email-verification.service.spec.ts
src/email-verification/email-verification.service.ts
src/email-verification/email/email.service.ts
src/email-verification/entities/user.entity.ts

email verification module added

---

docs/accessibility-guidelines.md
docs/accessibility-implementation-summary.md
docs/accessibility-testing-guide.md
package.json
scripts/accessibility-audit.js
src/common/middleware/accessibility.middleware.ts
src/user-settings/accessibility.controller.ts
src/user-settings/dto/create-user-setting.dto.ts
src/user-settings/entities/user-setting.entity.ts

- Add WCAG 2.1 AA compliant accessibility guidelines
- Enhance user settings with accessibility preferences
- Create accessibility controller and API endpoints
- Implement accessibility middleware
- Add testing guide and automated audit script
- Update package.json with accessibility scripts
Addresses: Create Accessibility Guidelines issue

feat: implement comprehensive accessibility guidelines and framework

---

src/content-management/content.controller.spec.ts
src/content-management/content.controller.ts
src/content-management/content.module.ts
src/content-management/dto/content-query.dto.ts
src/content-management/dto/create-content.dto.ts
src/content-management/dto/update-content.dto.ts
src/content-management/dto/upload-media.dto.ts
src/content-management/entities/content-media.entity.ts
src/content-management/entities/content-version.entity.ts
src/content-management/entities/content.entity.ts
src/content-management/enums/content.enum.ts
src/content-management/exceptions/content.exceptions.ts
src/content-management/interceptors/content-transform.interceptor.ts
src/content-management/interfaces/content.interface.ts
src/content-management/pipes/content-validation.pipe.ts
src/content-management/services/content-scheduler.service.ts
src/content-management/services/content.service.spec.ts
src/content-management/services/content.service.ts
src/content-management/services/media.service.ts

Content management API resource built

---

docs/database-optimization.md
src/config/database.config.ts
src/monitoring/database-monitoring.service.ts
src/users/entities/user.entity.ts
src/users/users.service.spec.ts
src/users/users.service.ts

This PR addresses the high-priority performance task: **Optimize Database Query Performance**.  
It focuses on profiling, optimizing slow queries, adding indexes, improving error handling, and documenting the strategy.
---
- Enabled slow query logging in TypeORM config (`logging: ['query', 'error', 'warn', 'slow']`)
- Set `maxQueryExecutionTime` to 500ms to identify expensive queries.
- Optimized `UserService.getActiveUsers()`:
- Added field selection (`select`)
- Added pagination (`take`)
- Added filtering (`where: { isActive: true }`)
- Sorted using indexed field (`createdAt`)
-  Database Monitoring Services
- Added indexes in `user.entity.ts`:
- `@Index(['email'])`
- `@Index(['isActive'])`
- `@Index(['createdAt'])`
- Wrapped DB calls in `try-catch`
- Logged errors and returned clean …

Optimize Database Query Performance

---

src/config/emailConfig.ts
src/notifications/config/notification.config.ts
src/notifications/controllers/notification-admin.controller.ts
src/notifications/controllers/notifications.controller.ts
src/notifications/decorators/notification-type.decorator.ts
src/notifications/dto/create-notification.dto.ts
src/notifications/dto/notification-preferences.dto.ts
src/notifications/entities/device-token.entity.ts
src/notifications/entities/notification-preferences.entity.ts
src/notifications/entities/notification.entity.ts
src/notifications/guards/notification-access.guard.ts
src/notifications/interceptors/notification-rate-limit.interceptor.ts
src/notifications/middleware/notification-logging.middleware.ts
src/notifications/migrations/001-create-notifications-tables.ts
src/notifications/pipes/notification-validation.pipe.ts
src/notifications/services/bulk-notification.service.ts
src/notifications/services/device-management.service.ts
src/notifications/services/notification-analytics.service.ts
src/notifications/services/notification-queue.service.ts
src/notifications/services/notification-retry.service.ts
src/notifications/services/notification-scheduler.service.ts
src/notifications/services/notification-template.service.ts
src/notifications/services/push-notification.service.ts
src/notifications/templates/notification-templates.ts
src/notifications/tests/notification-templates.spec.ts
src/notifications/tests/push-notification.service.spec.ts
src/notifications/types/notification.types.ts
src/notifications/utils/notification.utils.ts

closes #176 
This PR introduces a push notification service designed to send alerts to mobile devices across multiple platforms. It includes support for customizable templates, scheduling, and user preferences.  
- Created push notification service infrastructure  
- Integrated support for multiple platforms (e.g., iOS, Android)  
- Developed reusable notification templates  
- Added scheduling capabilities for delayed or timed delivery  
- Implemented user-specific notification preferences  
- Documented notification types and usage guidelines  
- Handled errors gracefully for delivery failures and integration issues  
- Added comprehensive tests for delivery logic and template rendering  
Run automated test suite using  
```bash
npm run test
```  
to verify functionality and edge cases …

Feat: Implemented push notification service

---

src/gamification/controllers/gamification.controller.spec.ts
src/gamification/controllers/gamification.controller.ts
src/gamification/dto/create-achievement.dto.ts
src/gamification/dto/create-reward.dto.ts
src/gamification/dto/leaderboard-query.dto.ts
src/gamification/dto/progress.dto.ts
src/gamification/entities/achievement.entity.ts
src/gamification/entities/gamification-event.entity.ts
src/gamification/entities/leaderboard-entry.entity.ts
src/gamification/entities/reward.entity.ts
src/gamification/entities/user-achievement.entity.ts
src/gamification/entities/user-reward.entity.ts
src/gamification/gamification.module.ts
src/gamification/services/achievement.service.spec.ts
src/gamification/services/achievement.service.ts
src/gamification/services/gamification-event.service.spec.ts
src/gamification/services/gamification-event.service.ts
src/gamification/services/leaderboard.service.spec.ts
src/gamification/services/leaderboard.service.ts
src/gamification/services/reward.service.spec.ts
src/gamification/services/reward.service.ts
src/progress/progress.service.ts

This PR adds backend infrastructure and features to support gamification elements including achievements, rewards, leaderboards, and engagement tracking. The system is designed to encourage user activity and improve retention by offering incentives and competition.
---
- **Achievement Entity**: Stores achievement ID, title, description, and point value.
- **Reward Entity**: Defines reward criteria, type, and redemption info.
- **UserProgress Entity**: Tracks accumulated points, unlocked achievements, and rewards received.
- Points awarded for specific user actions.
- Achievements automatically unlocked upon reaching conditions.
- Rewards triggered and stored based on defined criteria.
- Dynamic leaderboard generation based on user points.
- Aggregation and logging of gamification events. …

Implement Gamification Backend Systems

---

src/webhook/controllers/webhook-admin.controller.ts
src/webhook/controllers/webhook.controller.ts
src/webhook/decorators/webhook-event.decorator.ts
src/webhook/dto/create-webhook.dto.ts
src/webhook/dto/update-webhook.dto.ts
src/webhook/dto/webhook-event.dto.ts
src/webhook/entities/webhook-delivery.entity.ts
src/webhook/entities/webhook.entity.ts
src/webhook/examples/usage-examples.ts
src/webhook/interceptors/webhook-event.interceptor.ts
src/webhook/migrations/001-create-webhook-tables.ts
src/webhook/services/webhook-delivery.service.ts
src/webhook/services/webhook-event.service.ts
src/webhook/services/webhook.service.ts
src/webhook/tasks/webhook-retry.task.ts
src/webhook/webhook.module.ts

This PR implements a webhook system to enable real-time event notifications to external systems. It introduces an event notification framework, supports external integrations, and enhances the platform's real-time capabilities.
**Key Features:**
* Webhook delivery system
* Event trigger and dispatch logic
* External system integration support
* Basic webhook monitoring
**Closes #278

web hook system integration

---

src/certification/certification.module.ts
src/certification/controllers/certificate.controller.ts
src/certification/controllers/certification-type.controller.ts
src/certification/controllers/skill-assessment.controller.ts
src/certification/dto/create-certificate.dto.ts
src/certification/dto/create-certification-type.dto.ts
src/certification/dto/create-skill-assessment.dto.ts
src/certification/dto/start-assessment.dto.ts
src/certification/dto/submit-assessment.dto.ts
src/certification/dto/update-certification-type.dto.ts
src/certification/entities/assessment-attempt.entity.ts
src/certification/entities/certificate-verification.entity.ts
src/certification/entities/certificate.entity.ts
src/certification/entities/certification-type.entity.ts
src/certification/entities/skill-assessment.entity.ts
src/certification/examples/usage-examples.ts
src/certification/migrations/001-create-certification-tables.ts
src/certification/services/certificate-generator.service.ts
src/certification/services/certificate-verification.service.ts
src/certification/services/certificate.service.ts
src/certification/services/certification-type.service.ts
src/certification/services/skill-assessment.service.ts

This PR introduces a complete certification system to validate course completion and freelancer skills.
**Key Features:**
* Certificate generation with verification
* Skill assessment framework
* Support for multiple certification types
* Basic certification analytics
**Closes #272

implemented the certification functionality

---

docs/backup-recovery.md
src/backup/backup.service.spec.ts
src/backup/backup.service.ts
src/email/templates/backup-failure.hbs

closes #254 
This PR implements a robust, automated data backup and recovery system for the platform, addressing all critical risks of data loss and ensuring operational resilience. The solution includes automated backups, verification, point-in-time recovery (PITR) documentation, disaster recovery planning, and regular recovery testing procedures.
---
- **Automated Daily Backups:**  
- Scheduled daily PostgreSQL database backups using NestJS cron jobs.
- Local disk storage with retention policy.
- **Automated Backup Verification:**  
- Each backup is automatically verified by restoring to a test database.
- Failures trigger immediate email alerts to the admin.
- **Email Alerting:**  
- Integrated with the platform’s email system.
- New `backup-failure` email template for alerting on …

implemented the backup and recovery

---

src/config/config-service.ts
src/config/config-validation.ts
src/config/config.module.ts
src/config/defaults.ts
src/config/index.ts
src/config/managers.ts
src/config/schema.ts
src/config/types.ts

🔧 Implement Centralized Configuration Management System
Summary
Implements a comprehensive configuration management system to address scattered configuration files and missing environment-specific validation. This PR establishes a centralized, validated, and well-documented configuration system.
🎯 Resolves Issue
Implement Configuration Management - Medium Priority Operations Task
🚀 Changes Made
✅ Centralized Configuration System
Created unified EnvironmentVariables class with nested DTOs for all config sections
Consolidated app, server, database, Redis, and logging configurations
Implemented type-safe configuration structure with proper TypeScript interfaces
✅ Environment-Specific Validation
Added environment-aware validation classes (DevelopmentEnvironmentVariables, …

feat:Implement Configuration Management #247

---

src/caching/cache.service.ts
src/caching/caching.module.ts

closes #232 
This pull request introduces a **comprehensive caching strategy** aimed at improving the overall performance, scalability, and responsiveness of the application. By leveraging efficient caching mechanisms at critical layers of the system, we aim to reduce redundant computations, minimize database hits, and enhance user experience.
* ✅ Integrated in-memory caching (e.g., `NodeCache`, `Redis`, or custom layer depending on tech stack).
* ✅ Cached frequently accessed data such as:
* User profile information
* Public content and metadata
* Static configuration settings
* ✅ Implemented cache invalidation strategies to ensure data consistency after:
* Data mutations (create, update, delete)
* Time-based expiration (TTL)
* ✅ Abstracted cache logic into a reusable utility/service …

caching system

---

src/analytics-system/analytics.controller.ts
src/analytics-system/analytics.module.ts
src/analytics-system/analytics.service.spec.ts
src/analytics-system/analytics.service.ts
src/analytics-system/dto/analytics-query.dto.ts
src/analytics-system/dto/generate-report.dto.ts
src/analytics-system/dto/predict-completion.dto.ts
src/analytics-system/dto/report-export.dto.ts
src/analytics-system/entities/course-completion-prediction.entity.ts
src/analytics-system/entities/course-engagement-metric.entity.ts
src/analytics-system/entities/report-generation-job.entity.ts
src/analytics-system/interfaces/analytics.interface.ts
src/analytics-system/services/analytics-data.service.ts
src/analytics-system/services/predictive-analytics.service.ts
src/analytics-system/services/realtime-analytics.service.ts
src/analytics-system/services/reporting.service.ts

closes #238 
This PR introduces the **Advanced Course Analytics** feature, designed to give instructors and admins deeper insights into course performance, learner engagement, and overall platform effectiveness. The analytics cover metrics that go beyond basic completion rates—focusing on real-time interaction, session trends, progress drop-offs, and more.
---
* **User Progress Tracking**
Detailed per-user tracking to monitor video watch time, quiz scores, assignment submissions, and section completions.
* **Course Engagement Overview**
Summarized data visualizations showing:
* Average time spent on each course module
* Drop-off points per content section
* Most engaging modules or lessons
* **Daily/Weekly Active Users**
Charts displaying user activity trends over time for specific …

Implement Advanced Course Analytics

---

docs/api-versioning-implementation.md
src/common/decorators/api-version.decorator.ts
src/common/guards/version.guard.ts
src/common/middleware/version-header.middleware.ts
src/common/services/api-deprecation.service.ts
src/common/services/api-documentation.service.ts
src/common/services/api-versioning.service.ts
src/common/services/backward-compatibility.service.ts
src/config/api-version.config.ts
src/modules/version/documentation.controller.ts
src/modules/version/version.controller.ts
test/api-versioning.e2e-spec.ts

Feat api versioning

---

src/database-optimization/__tests__/query-analyzer.service.spec.ts
src/database-optimization/database-optimization.module.ts
src/database-optimization/interfaces/optimization-config.interface
src/database-optimization/interfaces/optimization-config.interface.ts
src/database-optimization/interfaces/query-analysis.interface
src/database-optimization/interfaces/query-analysis.interface.ts
src/database-optimization/services/performance-monitor.service.ts
src/database-optimization/services/query-analyzer.service.ts

This PR introduces the **Database Query Optimization** module aimed at improving query execution speed, reducing server load, and enhancing overall system performance.
**Key Changes:**
* Added query optimization logic to reduce redundant database calls.
* Implemented indexing strategies for high-traffic tables.
* Optimized complex join operations for better execution plans.
* Updated repository/service methods to leverage optimized queries.
* Added monitoring hooks to track query performance metrics.
**Benefits:**
* Faster data retrieval and response times.
* Lower database CPU and memory usage.
* Improved scalability for high concurrent traffic.
**Testing & Validation:**
* Verified performance gains through query benchmarking.
* All existing tests passed without regression.
* Monitored …

Implement Database Query Optimization Module

---

src/monitorings/__tests__/monitoring.service.spec.ts
src/monitorings/interfaces/monitoring-config.interface.ts
src/monitorings/interfaces/observability.interface.ts
src/monitorings/monitoring.module.ts
src/monitorings/services/alert.service.ts
src/monitorings/services/health-check.service.ts
src/monitorings/services/logger.service.ts
src/monitorings/services/metrics-collector.service.ts

This PR introduces the **Monitoring & Observability** module to improve system reliability, performance tracking, and issue diagnosis.
Key additions include:
* **Metrics Collection:** Integrated tools for tracking application performance metrics (CPU, memory, response times, request throughput).
* **Logging:** Structured and centralized logging for better traceability and debugging.
* **Health Checks:** Endpoints and checks to monitor service availability and responsiveness.
* **Alerting:** Configured alerts for critical failures, high error rates, and performance degradation.
* **Dashboard Integration:** Linked metrics and logs to visualization tools for real-time monitoring.
**Impact:**
* Enables proactive detection of issues before they escalate.
* Provides actionable insights into …

Implement Monitoring & Observability Module

---

src/data-quality/README.md
src/data-quality/__tests__/data-governance.service.spec.ts
src/data-quality/__tests__/data-quality-monitoring.service.spec.ts
src/data-quality/__tests__/data-quality.decorators.spec.ts
src/data-quality/__tests__/integration/data-quality-flow.spec.ts
src/data-quality/config/data-quality.config.ts
src/data-quality/data-quality.module.ts
src/data-quality/decorators/data-quality.decorators.ts
src/data-quality/services/data-quality-monitoring.service.ts

This PR delivers a **comprehensive Data Quality Management system** for the StrellerMinds platform, ensuring data integrity, governance, and real-time monitoring across the application.
* **Data Validation Decorators** (`decorators/data-quality.decorators.ts`)
* 20+ reusable decorators for common data types
* Configurable severity levels & thresholds
* Validation support for emails, phone numbers, URLs, credit cards, IP addresses, etc.
* **Enhanced Monitoring Service** (`services/data-quality-monitoring.service.ts`)
* Real-time metrics tracking with health status calculation
* Performance metrics & automated threshold monitoring
* Event-based alerting system for anomalies
* **Configuration System** (`config/data-quality.config.ts`)
* Environment-driven configuration options
* Monitoring, …

Data-Quality-Management-Implementation

---

development.env.example
src/auth/auth.controller.ts
src/certification/controllers/certificate.controller.ts
src/common/decorators/rate-limit.decorator.ts
src/common/guards/custom-throttler.guard.ts
src/config/rate-limit.config.ts
src/files/files.controller.ts
src/modules/auth/controllers/auth.controller.v1.ts
src/modules/auth/controllers/auth.controller.v2.ts
src/submission/submission.controller.ts
src/verification/verification.controller.ts
src/video-streaming/controllers/video-streaming.controller.ts
src/wallet-integration/controllers/wallet.controller.ts
test/rate-limiting.e2e-spec.ts

This PR introduces granular, per-endpoint rate limiting using the @nestjs/throttler module to enhance abuse prevention and protect high-risk application resources.
While a global rate limit is already configured, critical endpoints—specifically those related to Authentication, File Management, and Blockchain Interactions—require stricter, more tailored policies to safeguard against brute-force attacks and resource exhaustion.
The new configuration is centralized and fully environment-variable configurable, allowing DevOps/QA teams to easily tune limits across different deployment environments (e.g., staging vs. production) without code changes.
⚙️ Technical Plan & Changes
New Configuration File (src/config/rate-limit.config.ts):
Created a central object to define TTL (Time to Live) and …

Implement Per-Endpoint Rate Limiting & Abuse Protection Policies

---

src/app.module.ts
src/billing/billing.controller.ts
src/billing/billing.module.ts
src/billing/billing.service.ts
src/billing/premium-content.guard.ts
src/billing/tier.config.ts
src/courses/courses.controller.ts
src/courses/courses.module.ts
src/courses/dtos/create.course.dto.ts
src/courses/entities/course.entity.ts
src/migrations/1727650800-AddBillingColumns.ts
src/payment/stripe.service.ts
src/payment/subscription.service.ts
src/users/entities/user.entity.ts
src/users/services/users.service.ts

This PR implements a professional billing setup powered by **Stripe**, including:
* **Subscription tiers** with seat-based quantities and optional metered usage.
* **Self-serve customer portal** for managing billing details.
* **Premium course gating** integrated with existing webhook handling.
* **Persistence alignment** for subscription state and access control.
* **Audit logging** for key billing actions.
* Webhook handling was already in place; this PR ensures persistence and gating are properly aligned.
* Audit logs provide traceability for subscription changes and access decisions.
Please confirm if you’d like me to:
1. Run the migration script now.
2. Add integration tests in this PR.
3. Implement a usage-reporting endpoint.
closes #385

Implemented a professional billing setup using Stripe with:

---

.github/workflows/mutation-testing.yml
.gitignore update
.strykerignore
package.json
src/config/documentation.ts
stryker.conf.json

What I did:
✅ Runs mutation testing on PRs that modify src/ files
✅ Enforces 80% mutation score threshold (CI fails if below)
✅ Publishes HTML report as downloadable artifact
✅ Comments on PRs with mutation score summary
✅ Spins up PostgreSQL service for tests that need a database
✅ Excludes DTOs, entities, modules (boilerplate code)

feat:nforce Mutation Testing in CI with Stryker Thresholds #374

---

src/ipfs-backup/backup-cron.service.ts
src/ipfs-backup/dto/upload-asset.dto.ts
src/ipfs-backup/entities/asset.entity.ts
src/ipfs-backup/entities/cid-record.entity.ts
src/ipfs-backup/ipfs-backup.service.ts
src/ipfs-backup/ipfs.config.ts
src/ipfs-backup/ipfs.controller.ts
src/ipfs-backup/ipfs.module.ts
src/ipfs-backup/ipfs.service.ts

ipfs backup implementation

---

.github/workflows/database-migration-check.yml
docs/CI_CD_PIPELINE_GUIDE.md

This pull request introduces a new GitHub Actions workflow to serve as a database migration gate, ensuring that all migrations are synchronized before code is merged. This helps prevent deployment failures caused by database schema mismatches.
The new CI job automatically validates migrations on every pull request to main, develop, and staging.
Key Changes
New Workflow: Added .github/workflows/database-migration-check.yml.
Migration Validation: The CI job performs the following steps:
Sets up a temporary PostgreSQL database.
Runs all migrations to bring the schema up to date.
Executes db:validate and db:status to check for pending migrations or inconsistencies.
CI Gate: The workflow will fail if any pending migrations or validation errors are detected, blocking the PR from being merged. …

Database Migration Gate in CI
